Ventalis/urls.py
from django.conf import settings # new
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from api import consultant_views, customer_views
from api.consultant_views import OrderItemUpdateView, ConsultantOrderItemsView
from api.customer_views import ViewCustomerConsultant
from api.message_views import CustomerApiMessageViewSet, ApiMessageCreateView, ConsultantApiMessageViewSet, \
    MessagesWrittenByCustomerApiMessageViewSet, ConsultatReadApiMessageViewSet, CustomerApiMessageCreateView

router = DefaultRouter()
# router.register(r'newusers', views.NewUserViewSet)
#router.register(r'customer-messages', CustomerApiMessageViewSet, basename='customer-message')

from Ventalis import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('', include('store.urls')),
    path('', include('api.urls')),
    path('', include('contact.urls')),
    # API patths

    path('consultant-orderitems/', ConsultantOrderItemsView.as_view(), name='consultant_orderitems'),
    path('consultant-orderitem-update/<int:pk>/', OrderItemUpdateView.as_view(), name='orderitem_update'),

    path('consultant-create-message/', ApiMessageCreateView.as_view(), name='consultant-create-message'),
    path('consultant-sent-messages/', ConsultantApiMessageViewSet.as_view({'get': 'list'}),name='consultant-sent-messages'),
    path('consultant-read-messages/', ConsultatReadApiMessageViewSet.as_view({'get': 'list'}), name='consultant-read-messages'),

    path('customer-create-message/', CustomerApiMessageCreateView.as_view(), name='customer-create-message'),
    path('customer-sent-messages/', MessagesWrittenByCustomerApiMessageViewSet.as_view({'get': 'list'}),name='customer-sent-messages'),
    path('customer-read-messages/', CustomerApiMessageViewSet.as_view({'get': 'list'}), name='customer-read-messages'),


    path('customer-consultant/', ViewCustomerConsultant.as_view(), name='view-customer-consultant'),

    path('customer-orderitems/', customer_views.OrderItemListAPIView.as_view(), name='order_item_list'),
    path('customer-orderitem/<int:id>/', customer_views.OrderDetailAPIView.as_view(), name='order_detail'),




    path('api-auth/', include('rest_framework.urls')),
    path("api/", include(router.urls)),
    path('api/schema/',SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/',SpectacularSwaggerView.as_view(url_name='schema')),

    path('reset-password/',
       PasswordResetView.as_view(template_name="registration/password_reset.html"),
       name='reset_password'),
    path('reset-password/done/',
       PasswordResetDoneView.as_view(template_name='registration/password_reset_done1.html'),
       name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
       PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm1.html'),
       name='password_reset_confirm'),
    path('reset-password/complete/',
       PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete1.html'),
                       name='password_reset_complete'),

])

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # to render the photos uploaded if not 404
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

api/urls.py
from django.urls import path

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
#from .admin_views import get_all_consultants
from .admin_views import AllConsultantsView, ConsultantCreateView, ConsultantDetailView, ConsultantDeleteView
from .views import LogoutView

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/logout/', LogoutView.as_view(), name='token_blacklist'),
    #path('api-consultants/', get_all_consultants, name='get_all_consultants'),
    path('api-consultants/', AllConsultantsView.as_view(), name='show-consultants'),
    path('api-create-consultant/', ConsultantCreateView.as_view(), name='create-consultant'),
    path('api-retreive-consultant/<int:pk>', ConsultantDetailView.as_view(), name='retreive-consultant'),
    #path('api-update-consultant/<int:pk>', ConsultantUpdateView.as_view(), name='update-consultant'),
    path('api-delete-consultant/<int:pk>', ConsultantDeleteView.as_view(), name='delete-consultant'),

]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView

from .views import ConsultantCreateView, ConsultantDeleteView, CustomerListView

urlpatterns=[
    path('', views.home, name="home"),
    path('presentation/', views.presentation, name="presentation"),

    path('signup/', views.signup, name='signup'),
    #path('consultant-signup/', views.consultant_signup, name='consultant-signup'),

    #path("customers/", CustomerListView.as_view(), name="customers"),
    path("customers/", views.customers_relations, name="customers"),
    # path("all-users/", NewUserListView.as_view()),
    path('login/', views.WebAppLoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    #path('customer/<int:id>/',views.CustomerHome.as_view(), name="customer-home"),
    path("consultants/", ConsultantCreateView.as_view(), name="consultants"),
    # path("consultants/", ConsultantListView.as_view(), name="consultants"),
    # path('consultant/create/', ConsultantCreateView.as_view(), name='consultant-create'),
    path('consultant/delete/<int:pk>/', ConsultantDeleteView.as_view(), name='consultant-delete'),
    #path('consultant/update/<int:pk>/', ConsultantUpdateView.as_view(), name='consultant-update'),
    path('customer/profile/', views.customer_profile, name='customer-profile'),


]

store/models.py
import random
import string
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.utils import timezone
from django.db.models.signals import pre_save


class Category(models.Model):
    name = models.CharField(_("Nom"), max_length=255, unique=True)
    slug = models.SlugField(_("Slug"), max_length=255, blank=True)

    class Meta:
        """Meta definition for Category."""
        verbose_name = _("Catégorie")
        verbose_name_plural = _("Categories")
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f'/{self.slug}/'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name=_("Catégorie"), on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(_("Nom"), max_length=255)
    description = models.TextField(_("Description"), blank=True)
    price = models.DecimalField(_("Prix"), max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(_("Prix"), max_digits=10, decimal_places=2, blank=True, null=True)
    image = models.ImageField(_("Image"), upload_to='products/', null=True, blank=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    slug = models.SlugField(_("Slug"), unique=True, max_length=255)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Produit")
        verbose_name_plural = _("Produits")
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url= ''
        return url

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("product", kwargs={"slug":self.slug})
    def __str__(self):
        return self.name

    def display_1000_units_price(self):
        return self.price * 1000

class Order(models.Model):
    customer = models.ForeignKey('users.Customer', verbose_name=_("Client"), on_delete=models.CASCADE)
    transactionId = models.CharField(max_length=20, blank=True, null=True)
    date_ordered = models.DateTimeField(_("Date de commande"), auto_now_add=True)
    completed = models.BooleanField(_("Commande complète"), default=False)
    comment = models.TextField(verbose_name=_("Commantaire sur commande"), blank=True, null=True)

    class Meta:
        ordering = ("-date_ordered",)
    def __str__(self):
        return str(self.id)
    def has_high_quantity_items(self):
        orderitems = self.orderitem_set.all()
        for orderitem in orderitems:
            if orderitem.quantity >= 1000:
                return True
        return False

    @property
    def need_shipping_address(self):
        from users.models import Address # # Import Address locally, not at the beginning of the file, if not circular import issue
        # Check if the user has associated address.
        return not Address.objects.filter(user=self.customer).exists()

    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    def get_transaction_id(self):  # Generate a random transaction ID
        return ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))

class OrderItem(models.Model):
    class Status(models.TextChoices):
        PENDING = 'P', _('En attente')
        PROCESSING = 'PR', _('En traitement')
        SHIPPED = 'S', _('Expédié')
        DELIVERED = 'D', _('Livré')
        RETURNED = 'R', _('Retourné')

    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.PENDING,
        verbose_name=_("Statut de la commande"),
    )

    customer = models.ForeignKey('users.Customer', verbose_name=_("Client"), on_delete=models.CASCADE)
    order = models.ForeignKey(Order, verbose_name=_("Commande"), on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, verbose_name=_("Produit"), on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(_("Quantité"), default=1000)
    comment = models.TextField(verbose_name=_("Commantaire sur articles"), blank=True, null=True)
    date_added = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ("-date_added",)

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

    @property
    def get_total_discount_price(self):
        total = self.product.discount_price * self.quantity
        return total

    def get_absolute_url(self):
        return reverse('change_order_itemr', args=[str(self.id)])

class OrderItemStatusHistory(models.Model):
    order_item = models.ForeignKey('OrderItem', verbose_name=_("Article de commande"), on_delete=models.CASCADE)
    consultant = models.ForeignKey('users.Consultant', verbose_name=_("Consultant"), on_delete=models.CASCADE)
    customer = models.ForeignKey('users.Customer', verbose_name=_("Client"), on_delete=models.CASCADE)
    status = models.CharField(
        max_length=2,
        choices=OrderItem.Status.choices,
        verbose_name=_("Nouveau statut de la commande"),
    )
    comment = models.TextField(verbose_name=_("Commentaire sur la modification"), blank=True, null=True)
    date_modified = models.DateTimeField(_("Date de modification"), auto_now_add=True)

    def __str__(self):
        return f"{self.order_item} - {self.status}"

    @receiver(pre_save, sender=OrderItem)
    def create_order_item_status_history(sender, instance, **kwargs):
        # Vérifier si l'objet OrderItem a déjà été enregistré en base de données (mise à jour plutôt que création)
        if instance.pk is not None:
            # Récupérer l'objet OrderItem enregistré en base de données pour comparer les changements
            old_order_item = OrderItem.objects.get(pk=instance.pk)
            # Récupérer le client associé à l'OrderItem
            customer = instance.customer

            # Récupérer le consultant associé au client
            consultant = customer.consultant_applied

            # Vérifier si le statut ou le commentaire a changé
            if instance.status != old_order_item.status or instance.comment != old_order_item.comment:
                # Enregistrer l'historique du statut
                OrderItemStatusHistory.objects.create(
                    order_item=instance,
                    consultant=consultant,
                    customer=customer,  # Utiliser le client associé à l'OrderItem
                    status=instance.status,
                    comment=instance.comment
                )

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from store.models import Category
from .models import Consultant, Customer
#from .validators import ContainsLetterValidator, ContainsNumberValidator, ContainsSpecialCharacterValidator, MinimumLengthValidator


class ConsultantCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label='Prénom', help_text='Champ obligatoire. Entrez le prénom de l\'employé')
    last_name = forms.CharField(max_length=30, required=True,label='Nom de famille', help_text='Champ obligatoire. Entrez le nom de famille de l\'employé')

    class Meta:
        model = Consultant
        fields = [
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super(ConsultantCreationForm, self).__init__(*args, **kwargs)

        # Ajouter des attributs ou modifier les champs si nécessaire
        for field_name in ['first_name', 'last_name', 'password1', 'password2']:
            self.fields[field_name].widget.attrs.update({'class': 'form-control'})

        # Supprimer le help_text par défaut pour les mots de passe
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

        # Ajouter un message d'aide pour les mots de passe
        # self.fields['password1'].widget.attrs.update({'placeholder': 'Entrez le mot de passe'})
        # self.fields['password2'].widget.attrs.update({'placeholder': 'Confirmez le mot de passe'})


class CustomerCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label='Prénom')
    last_name = forms.CharField(max_length=30, required=True, label='Nom de famille')
    company = forms.CharField(max_length=30, required=True, label='Société')

    class Meta:
        model = Customer
        fields = [
            'company',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

users/templates/users/consultant_create.html
{% extends "base.html" %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="button" class="btn btn-outline-success custom-button rounded">Success</button>
  </form>
{% endblock %}

users/templates/users/consultant_list.html
{% extends "base.html" %}

{% block content %}


{% if messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}


<div class="row">
    <h2 class="text-success mt-2 mb-3">Créer un consultant</h2>
    <form method="post" id="consultant-form"  action="{% url 'consultants' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="custom-button" type="submit">Enregistrer</button>
    </form>
</div>
<hr>
<div class="row">
    <h2 class="text-success mt-2 mb-3">Gestion des consultants existants</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-responsive text-secondary align-middle">
            <thead class="thead-dark">
                <tr>
                    <th>Matricule</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Date d'embouche</th>
                    <th>Nombre de clients</th>
                    <th class="center_my-text">ID DB</th>
                    <th class="center_my-text">Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for consultant in consultants %}
                    <tr>
                        <td>{{ consultant.matricule }}</td>
                        <td>{{ consultant.first_name }}</td>
                        <td>{{ consultant.last_name | upper }}</td>
                        <td>{{ consultant.email }}</td>
                        <td>{{ consultant.date_joined }}</td>
                        <td>{{ consultant.clients.count }}</td>
                        <td class="align-items-center">{{consultant.pk}}</td>
                        <td class="center_my-text">
                           <a href="{% url 'consultants' %}?pk={{ consultant.pk }}"><i class="fas fa-edit"></i></a>
                                                                           <!-- Bouton pour ouvrir le modal -->
                        <button class="btn modal-supprimer" data-bs-toggle="modal"  data-bs-target="#deleteModal{{ consultant.pk  }}">
                        <i class="fas fa-trash"></i></button>
                            <a href="{% url 'consultants' %}"><i class="fas fa-undo-alt"></i></a>
                        </td>

                        <!-- Modal de confirmation -->
                    <div class="modal fade" id="deleteModal{{ consultant.pk  }}" tabindex="-1" role="dialog"
                        aria-labelledby="deleteModalLabel{{ consultant.pk  }}" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteModalLabel{{ consultant.pk }}">
                                        Confirmation de suppression</h5>
                                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Êtes-vous sûr de vouloir supprimer {{consultant.email}} de la liste ?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Annuler</button>
                                    <!-- Formulaire pour la suppression -->
                                    <form method="post" action="{% url 'consultant-delete' consultant.pk  %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn \F78B">Supprimer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
<!--                        fin de modal-->
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    </div>
{% endblock %}

users/templates/users/customer_list.html
{% extends "base.html" %}

{% block content %}

  <div class="container mt-5">
    <h2 class="mb-4">Consultants et leurs clients</h2>

    {% for consultant, clients in consultant_clients %}
      <div class="card mb-4 shadow">
        <div class="card-header">
          <h5 class="mb-0">{{ consultant.first_name }} {{ consultant.last_name |upper }} (Matricule: {{ consultant.matricule }})</h5>
        </div>
        <div class="card-body">
          {% if clients %}
            <ol class="list-group">
              {% for client in clients %}
                <li class="list-group-item">{{ client.company }} - {{ client.first_name }} {{ client.last_name|upper }} - contact : {{ client.email }}</li>
              {% endfor %}
            </ol>
          {% else %}
            <p>Pas de clients assignés encore.</p>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>


{% endblock %}

users/templates/users/customer_profile.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}
  <h2>Vos commandes</h2>

  <div class="mb-3">
    <h3 >Commandes payées</h3>

    {% if ordered_items %}
      {% for order_item in ordered_items %}
        <div class="card shadow mb-3 ">
          <div class="card-header" style="background-color: black; color: #0d9c43">
            <p>Order ID: {{ order_item.order.id }} | Transaction ID: {{ order_item.order.transactionId }}</p>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ order_item.product.name }}</h5>
            <p class="card-text">Quantity: {{ order_item.quantity }}</p>
            <p class="card-text">Price: {{ order_item.get_total | floatformat }} €</p>
            <p class="card-text">Date Added: {{ order_item.date_added|date:"Y-m-d H:i:s" }}</p>
            <p class="card-text">Status: {{ order_item.get_status_display }}</p>
            {% if order_item.comment %}
            <p class="card-text">Commentaire de votre consultant: {{ order_item.comment }}</p>
            {% else %}
            <p class="card-text">Pas de commentaire de votre consultant</p>
            {% endif %}

          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>Aucun article commandé trouvé.</p>
    {% endif %}
  </div>

  <div class="mb-3">
    <h3>Vos commandes en attente dans le panier</h3>

    {% if not_ordered_items %}
      {% for order_item in not_ordered_items %}
        <div class="card shadow">
          <div class="card-header" style="background-color: black; color: #0d9c43">
            <p>Order ID: {{ order_item.order.id }} | Transaction ID: {{ order_item.order.transactionId }}</p>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ order_item.product.name }}</h5>
            <p class="card-text">Quantity: {{ order_item.quantity }}</p>
            <p class="card-text">Price: {{ order_item.get_total | intcomma }} €</p>
            <p class="card-text">Date Added: {{ order_item.date_added|date:"Y-m-d H:i:s" }}</p>
            <p class="card-text">Status: {{ order_item.get_status_display }}</p>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>Pas d'articles non commandé.</p>
    {% endif %}
  </div>

{% endblock %}

users/templates/users/home_consultant.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
  {% if clients %}
    <div class="container mt-5 text-light" style="background-color: #f8f9fa; height: 90vh;">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-ms-8">
          <div class="card border-0 shadow-lg">
            <div class="card-header" style="background-color: #000000; color: #27b547;">
              <h4>Liste des commandes des clients (par société)</h4>
            </div>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Société</th>
                    <th>Commande</th>
                    <th>Prenom</th>
                    <th>Nom de famille</th>
                    <th>Email</th>
                    <th>Total</th>
                    <th class="d-sm-table-cell">Statut</th>
                    <th class="d-sm-table-cell">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for client in clients %}
                    {% for item in client.order_set.all %}
                      <tr>
                        {% if forloop.first %}
                          <td rowspan="{{ client.order_set.count }}">{{ client.company }}</td>
                        {% endif %}
                        <td><a href="{% url 'order-detail' pk=item.id %}" class="categorie-plus">{{ item }}</a></td>
                        <td>{{ client.first_name }}</td>
                        <td>{{ client.last_name }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ item.price | intcomma }} €</td>
                        <td class="d-sm-table-cell">
                          {% if item.ordered %}
                            Commandé
                          {% else %}
                            En attente
                          {% endif %}
                        </td>
                        <td class="d-sm-table-cell">
                          <a href="{% url 'consultant-order-update' item.id %}" class="btn custom-btn">
                            <i class="bi bi-pencil-fill me-2"></i>Editer
                          </a>
                        </td>
                      </tr>
                    {% empty %}
                      <tr>
                        {% if forloop.first %}
                          <td rowspan="{{ client.order_set.count }}">{{ client.company }}</td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  {% empty %}
                    <tr>
                      <td colspan="7">Aucun client pour le moment</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div>
      Aucun client pour le moment
    </div>
  {% endif %}
{% endblock %}

users/templates/users/my_orders.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<h5 class="card-title">Commandes en cours</h5>


{% endblock %}

users/templates/users/newuser_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Users</h2>
    <ul>
        {% for user in users %}
            <li>{{ user.first_name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}

{% block content %}

  <div class="row justify-content-center align-items-center h-100">
    <div class="col-md-8">
      <div class="card border-0 shadow-lg">
        <div class="card-header" style="background-color: #000000;">
          <h4 class="text-center" style="color: #0d9c43">Créer un compte</h4>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="company">Nom de la société</label>
              <input type="text" class="form-control form-control-lg{% if form.company.errors %} is-invalid{% endif %}" id="company" name="company">
              {% if form.company.errors %}
                <div class="invalid-feedback">
                  {% for error in form.company.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="first_name">Prénom</label>
              <input type="text" class="form-control form-control-lg{% if form.first_name.errors %} is-invalid{% endif %}" id="first_name" name="first_name">
              {% if form.first_name.errors %}
                <div class="invalid-feedback">
                  {% for error in form.first_name.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="last_name">Nom de famille</label>
              <input type="text" class="form-control form-control-lg{% if form.last_name.errors %} is-invalid{% endif %}" id="last_name" name="last_name">
              {% if form.last_name.errors %}
                <div class="invalid-feedback">
                  {% for error in form.last_name.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="email">Adresse e-mail</label>
              <input type="email" class="form-control form-control-lg{% if form.email.errors %} is-invalid{% endif %}" id="email" name="email">
              {% if form.email.errors %}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="password1">Mot de passe</label>
              <input type="password" class="form-control form-control-lg{% if form.password1.errors %} is-invalid{% endif %}" id="password1" name="password1">
              {% if form.password1.errors %}
                <div class="invalid-feedback">
                  {% for error in form.password1.errors %}
                      {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="password2">Confirmer le mot de passe</label>
              <input type="password" class="form-control form-control-lg{% if form.password2.errors %} is-invalid{% endif %}" id="password2" name="password2">
                {% if form.password2.errors %}
              <div class="invalid-feedback">
                {% for error in form.password2.errors %}
                  {{ error }}
                {% endfor %}
              </div>
              {% endif %}
            </div>
            <div class="text-center mt-4">
              <button type="submit" class="btn btn-success group-custom-button" style="background-color: #27b547; border-color: #27b547;">Envoyer</button>
            </div>
            {% if form.non_field_errors %}
              <div class="alert alert-danger mt-3" role="alert">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}

            </form>
          </div>
        </div>
      </div>
    </div>

{% endblock %}